spring:
    application:
        name: rabbitmq
    rabbitmq:
        host: localhost
        port: 5672
        username: guest
        password: guest
        virtual-host: /
queue:
    name: "queue"
